# Autor: Daniel Benjamin Perez Morales
# GitHub: https://github.com/D4nitrix13
# GitLab: https://gitlab.com/D4nitrix13
# Correo electrónico: danielperezdev@proton.me

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt

services:
  # -----------------------------------------------------------
  # 172.18.0.2 – POSTGRESQL
  # -----------------------------------------------------------
  postgresql:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    restart: always
    expose:
      - 5432/tcp
    ports:
      - 5433:5432/tcp
    secrets:
      - POSTGRES_PASSWORD
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD

  # -----------------------------------------------------------
  # 172.18.0.3 – LARAVEL APP
  # -----------------------------------------------------------
  app:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - 8000/tcp
    ports:
      - 8001:8000/tcp

  # -----------------------------------------------------------
  # 172.18.0.4 – PGADMIN
  # -----------------------------------------------------------
  pgadmin4:
    depends_on:
      - postgresql
    image: elestio/pgadmin
    restart: always
    expose:
      - 8080/tcp
    ports:
      - 8081:8080/tcp
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080

  # -----------------------------------------------------------
  # 172.18.0.5 – STRIPE WEBHOOK FORWARDER
  # -----------------------------------------------------------
  stripe:
    depends_on:
      - app
    image: stripe/stripe-cli:v1.29.0
    restart: always
    command: [ "listen", "--forward-to", "app:8000/stripe/webhook" ]

  # -----------------------------------------------------------
  # 172.18.0.6 – POSTGRES EXPORTER
  # -----------------------------------------------------------
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: unless-stopped
    expose:
      - 9187/tcp
    ports:
      - 9187:9187/tcp
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgresql:5432/${DB_DATABASE}?sslmode=disable"
    depends_on:
      - postgresql

  # -----------------------------------------------------------
  # 172.18.0.7 – PROMETHEUS
  # -----------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    expose:
      - 9090/tcp
    ports:
      - 9090:9090/tcp
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
      - postgres-exporter

  # -----------------------------------------------------------
  # 172.18.0.8 – GRAFANA
  # -----------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    expose:
      - 3000/tcp
    ports:
      - 3001:3000/tcp
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:
