global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "laravel-app"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "app:8000"

  # MÃ©tricas de PostgreSQL
  - job_name: "postgres"
    static_configs:
      - targets:
          - "postgres-exporter:9187"
